title: "Long Tom"
email: daril@longtom.ca
timezone: America/Edmonton
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
author: Daril
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  daril:
    name: Daril
    display_name: Daril
    avatar: 'assets/images/daril.png'
    email: daril@longtom.ca
    web: https://www.longtom.ca
    twitter: https://x.com/CamiloDaril
    description: "Polymath, Daril, is a sales specialist with expertise in various fields such as Human Resources management, Marketing, Political Science, and Game Development. With a broad perspective on business, exceptional interpersonal communication skills, bold leadership, and keen business acumen, he is the leader poised to become one of the biggest names in the gaming industry soon."
  john:
    name: Miguel Camilo<!-- Este é um comentário explicativo -->
    display_name: Miguel
    avatar: 'assets/images/john.png'
    email: miguel@longtom.ca
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Miguel is a commercial prospecting specialist, responsible for expanding Long Tom's roster of content creators and establishing key professional connections for the company in Brazil. He also serves as the company's official representative in the country."

# Social
social:
  instagram: https://www.instagram.com/longtom.ca/
  facebook: https://www.facebook.com/profile.php?id=61569114142627
  twitter: https://x.com/longtom_ca

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives